In [2]:
# numpy
import numpy as np

In [3]:
# cria uma matriz unidimensional
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [4]:
# criar um arrar com um tipo especifico
# cria um array como float de 64 bits
mtfloat = np.array([1,2,3], dtype=np.float64)
print(mtfloat)
print(type(mtfloat))

# int array
mtint = np.array([1,2,3], dtype=np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [5]:
# mudar o tipo do array
# podemos mudar tipos de dados de array
mtnew = np.array([1.4,3.6,-5.1,9.42])
print(mtnew)

# quando transformados de float para int os valores sao truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4   3.6  -5.1   9.42]
[ 1  3 -5  9]


In [8]:
# podemos fazer o inverso
mt5 = np.array([1,2,3,5,6])
print(mt5)

mt6 = mt5.astype(float)
print(mt6)

[1 2 3 5 6]
[1. 2. 3. 5. 6.]


In [9]:
# mais de uma dimensao
mt7 = np.array([[2,6,8], [1,4,6], [8,2,5]])
print(mt7)

[[2 6 8]
 [1 4 6]
 [8 2 5]]


In [13]:
# criar arrays com varios tipos
# empty significa que nao sao inicializados

vazio = np.empty([3,2], dtype=int)
print(vazio)
print("__________")
zeros = np.zeros([4,3])
print(zeros)
print("__________")
ones = np.ones([5,7])
print(ones)
# cria uma matriz quadrada com diagnonal principal com valores 1 e outros valores zero
diagonal = np.eye(5)
print(diagonal)

[[      164513623               0]
 [    12884901890              33]
 [125063548386096       170687024]]
__________
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
__________
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
# valores aleatorios entre zero e um
ale = np.random.random((5))
print(ale)

[0.10290921 0.75636473 0.83973723 0.91680673 0.4713231 ]


In [16]:
# valores aleatorios distibuidos normal contendo negativos
ale2 = np.random.randn((5))
print(ale2)

[-0.50818304 -1.01013408  0.22140852  0.6150185  -0.12067349]


In [17]:
# valores aleatorios 3 * 4
ale3 = (10 * np.random.random((3,4)))
print(ale3)

[[8.88575035 7.82402796 8.98731251 5.17788697]
 [5.92321616 6.51305959 3.67159508 0.18232577]
 [6.73617051 6.77848935 7.59795579 4.30318446]]


In [33]:
# outra forma de gerar valores aleatorios
# uso da semente

gnr = np.random.default_rng(1) # semente
# reproduzir o teste da mesma forma como foram gerados. sem mudar os dados tem que gerar uma semente

ale5 = gnr.random(3)
print(ale5)

# gerar inteiros
ale6 = gnr.integers(10, size=(3,4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [36]:
# metodo unique
j = np.array([11,2,3,6,7,2,3,11,14,2,3])
j = np.unique(j)
print(j)

[ 2  3  6  7 11 14]


In [41]:
# funcoes especificas

# criar uma matriz bidimensional
k = np.array([[11,4,5], [12,6,7], [9,12,10]])
print(k)

# mostrar elemento especifico da matriz
print(k[0][1])

# mostra o tamanho das dimensoes da matriz k
print(k.shape)

[[11  4  5]
 [12  6  7]
 [ 9 12 10]]
4
(3, 3)


In [53]:
# funcoes matematicas

# Mostrar o maior valor da matriz k
print(k.max())

# Mostrar o menor valor da matriz k
print(k.min())

# Mostrar a soma dos valores da matriz k
print(k.sum())

# Mostrar o valor da media dos valores da matriz k
print(k.mean())

# Mostrar o valor do desvio padrao (standard deviation) da matriz da matriz k
print(k.std())

12
4
76
8.444444444444445
2.8717439962933526


In [56]:
# funcoes universais, aplicadas a todos elementos
# Mostra o valor da raiz quadrada de todos elementos
k1 = np.array([1,4,9,16,25,36])
print(np.sqrt(k1))

# Mostra o valor do exponencial de todos elementos
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [64]:
# extracao de elementos
m = np.array([1,2,3,4,5,6])

# mostra o elemento na posicao 2
print(m[1])

# Mostra o array criado a partir dos elementos 0, dois elementos
print(m[0:2]) # os intervalos ignoram o ultimo valor sempre

# Mostra os elementos do array a partir da 2a posicao
print(m[1:])

# Mostra a partir da antepenultima
print(m[-3:])


2
[1 2]
[2 3 4 5 6]
[4 5 6]


In [75]:
# extracao de linhas e colunas
l = np.array([[4,6], [1,5], [9,4]])
print(l)

# primeira linha todos elementos
print(l[0, :])

# segunda linha todos elementos
print(l[1, :])

# terceira linha todos elementos
print(l[2, :])

# todas linhas primeira coluna
print(l[:, 0])

# todas linhas segunda coluna
print(l[:, 1])

[[4 6]
 [1 5]
 [9 4]]
[4 6]
[1 5]
[9 4]
[4 1 9]
[6 5 4]


In [82]:
# adicao e multiplicacao de matrizes
n = np.array([[1,2], [3,4]])
o = np.array([[1,1], [1,1]])

# soma
res1 = n+o
print(res1)

# multiplcacao
print(n*o)

# estruturas diferentes
mta = np.array([[2,5,4], [3,8,5], [2,6,4]])
mtb = np.array([[2,1,2]])
print(mta+mtb)

[[2 3]
 [4 5]]
[[1 2]
 [3 4]]
[[4 6 6]
 [5 9 7]
 [4 7 6]]


In [83]:
# transposicao - transformar linhas em colunas
f = np.arange(15).reshape((3,5))
print(f)

s = f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [85]:
# Outra forma de fazer mesmo resultado 
r = np.arange(15).reshape((3,5))
print(r)

s = r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [94]:
# expressoes logicas
# usando where
# criando matriz com valores aleatorios positivos e negativos
v = np.random.randn(4,4)
print(v)

# criando matriz com valores booleanos baseados na matriz v
x = (v > 0)
print(x)

# criando matriz com valores 1 e -1 baseado nos valores do array x
z = np.where(x > 0, 1, -1)
print(z)

[[-0.5765604   0.09581865 -1.22575596  1.96207736]
 [ 0.85646538  0.15451339  0.34228224  0.24696482]
 [ 0.17758697  1.2291152   0.9077877   0.72944566]
 [ 0.47526099 -1.98464204 -1.16873062 -0.16213404]]
[[False  True False  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True False False False]]
[[-1  1 -1  1]
 [ 1  1  1  1]
 [ 1  1  1  1]
 [ 1 -1 -1 -1]]
